USE [master]
GO

DECLARE @dbFilePath SYSNAME = N'$(dbFilePath)';
DECLARE @dbLogPath SYSNAME = N'$(dbLogPath)';

--DECLARE @dbFilePath SYSNAME = 'H:\UserData';
--DECLARE @dbLogPath SYSNAME = 'I:\UserLogs';
DECLARE @dbFilePathAndName NVARCHAR (255) ;
DECLARE @dbLogPathAndName NVARCHAR (255);

SET @dbFilePathAndName= @dbFilePath + '\DataQualityDB.mdf';
SET @dbLogPathAndName= @dbLogPath + '\DataQualityDB_log.ldf';

IF EXISTS (SELECT 1 FROM sys.databases WHERE name = 'DataQualityDB')
BEGIN
	ALTER DATABASE DataQualityDB SET SINGLE_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE DataQualityDB
END


/****** Object:  Database [DataQualityDB]    Script Date: 07/04/2016 13:48:18 ******/
declare @sqlstmt VARCHAR (MAX)
SET @sqlstmt =
'CREATE DATABASE [DataQualityDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N''DataQualityDB'', FILENAME = N'''+@dbFilePathAndName+''' , SIZE = 1048576KB , MAXSIZE = UNLIMITED, FILEGROWTH = 102400KB )
 LOG ON 
( NAME = N''DataQualityDB_log'', FILENAME = N'''+@dbLogPathAndName+''' , SIZE = 1048576KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
'

EXEC (@sqlstmt);

ALTER DATABASE [DataQualityDB] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DataQualityDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DataQualityDB] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DataQualityDB] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DataQualityDB] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DataQualityDB] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DataQualityDB] SET ARITHABORT OFF 
GO

ALTER DATABASE [DataQualityDB] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DataQualityDB] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [DataQualityDB] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DataQualityDB] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DataQualityDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DataQualityDB] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DataQualityDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DataQualityDB] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DataQualityDB] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DataQualityDB] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DataQualityDB] SET  DISABLE_BROKER 
GO

ALTER DATABASE [DataQualityDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DataQualityDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DataQualityDB] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DataQualityDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DataQualityDB] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DataQualityDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DataQualityDB] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DataQualityDB] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [DataQualityDB] SET  MULTI_USER 
GO

ALTER DATABASE [DataQualityDB] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DataQualityDB] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DataQualityDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DataQualityDB] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [DataQualityDB] SET  READ_WRITE 
GO


